---
access:
  username: your_bitbucket_username
  password: your_bitbucket_app_password

global:
   workspaceID: your_workspace_id
   repository_slug: your_repository_slug
   repository_uuid: your_repository_uuid

deploy_keys:
  - {
      label: test,
      key: your_public_key
    }

repositories_variables:
  - {
      key: some_variable_name,
      value: some_variable_name,
      secured: false
    }

production_variables:
  - {
      key: some_variable_name,
      value: some-variable-value,
      secured: true
    }

staging_variables:
  - {
      key: some_variable_name,
      value: some-variable-value,
      secured: false
    }

ssh_key:
  public_key: public_key
  private_key: private_key

known_hosts:
  - {
      hostname: '18.218.239.227:22',
      key_type: 'RSA', # Ed25519 ECDSA RSA DSA
      key: 'the plain pyblic key',
    }